### ISSUE TITLE
why does it depend on redix? 

### ISSUE THREAD

**Issue by JJPro** [chugunov/socketio_emitter#1]
I don't understand why this package relies on redix to emit messages. 
I'm trying to connect to a third party socket.io server and they don't have any information on redis support. 

Can I still use this to connect with their socket.io server? 
The socket.io server url I'm trying to connect is `https://ws-api.iextrading.com/1.0/tops` ([here's a example](https://iextrading.com/developer/docs/#websockets)), 
if this package can do it, how should I configure? 

Thanks

**Comment by chugunov** [comment]
@JJPro Hi. If you wanna connect to socket.io server using wss protocol and receive messages from it, you can use another library (for ex. [elixir-socket](https://github.com/meh/elixir-socket)). 

`socketio_emitter` helps you emit messages to socket.io server from Elixir applications, not listen to.

**Comment by JJPro** [comment]
Unfortunately the server uses https protocol. 
I've been using WebSockex for normal websocket connections. 
The server currently only support socket.io clients for their WebSocket server, I've been researching and trying out various packages whole day without luck.
Planning to build a nodejs program as a proxy between their server and my Elixir app.

**Comment by chugunov** [comment]
@JJPro socket.io uses long-polling or websocket transport. Did you try connect to `wss://ws-api.iextrading.com/1.0/tops`?
Anyway I think that building a nodejs proxy program is the best solution.
